version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-finance-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finance_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: